// AUTO-GENERATED by codegen_from_plan.py — DO NOT EDIT MANUALLY
// Source plan: spec/aes128_auto.yaml

package crypto.gen

import chisel3._
import chisel3.util._
import crypto.common._
import crypto.aes._

/** Placeholder AddRoundKey (auto-generated). Prefer using crypto.aes.AddRoundKey. */
class AddRoundKeyGen(p: CryptoParams) extends Module {
  val io = IO(new Bundle {
    val in  = Flipped(Decoupled(new Block(p)))
    val rk  = Input(new Key(p))
    val out = Decoupled(new Block(p))
  })
  io.out.valid := io.in.valid
  io.in.ready  := io.out.ready
  io.out.bits.bits := io.in.bits.bits ^ io.rk.bits
}
